---

 - name: Ping check
#   hosts: test_servers:DR
   hosts: LINUX7 rtfm
   gather_facts: no
#   become: yes
#   become_method: sudo


   vars:
#    ansible_ssh_private_key_file: "{{ hostvars[inventory_hostname].ansible_ssh_private_key_file }}"
#######    ansible_ssh_private_key_file: /home/gwilson1/.ssh/bofh.rsa

   tasks: 
   
    - name: Ping
#      become_user: "{{ hostvars[inventory_hostname].a_user }}"
#      remote_user: bofh
      ping:
